name: Build Mac App
on:
  workflow_dispatch:
  push:
    branches:
      - mirror
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mirror
      - name: Build
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install halibut
          mkdir build-mac
          cd build-mac
          cmake ..
          make -j4
          zip -r Puzzles.app.zip Puzzles.app

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Puzzles-mac-latest"
          prerelease: true
          title: "Puzzles Mac (Apple Silicon)"
          files: |
            build-mac/Puzzles.app.zip

